### PR TITLE
README improvements

### PR DESCRIPTION
**Pull request by OPNA2608**
- Moved File I/O section into a separate Markdown document.
- Dropped the custom section labels, GitHub already lets you link to specific sections.
- Prettied up the start of the document :)
- Shuffled around the sections & content abit

I have dropped the preview gif because it took up alot of valuable space wherever i tried to put it. Maybe it could be moved to the wiki? Or we could add a gallery section at the end of the readme instead.

### CODE REVIEW

**Comment by freq-mod** [comment]
Thanks :+1:

**Comment by OPNA2608** [comment]
You're welcome!

I'm noticing that i missed some things in an attempt to hurry up with the PR, you mind if I make the code suggestions on your PR or would you prefer if I fix them with another PR?

**Comment by freq-mod** [comment]
Feel free to make another PR, if you need

**Comment by freq-mod** [comment]
> Maybe it could be moved to the wiki?

Yeah, that can be a good idea. I don't feel like making gallery section for just one gif, to be honest.

**Pull request merged**
